#+TITLE: Curriculum Vitae
#+AUTHOR: Mohammad Razavi
#+KEYWORDS: vita, CV, resume
#+OPTIONS: toc:nil num:nil
#+STARTUP: entitiespretty

#+BEGIN_QUOTE
As a programmer, I specialize in back-end programming but beyond
application development I am expert in system design, scripting and
automation.

I have designed software and worked with teams to implement and
operate them over years. I love debugging, working on optimization
problems and solving challenges.  I have experience with developing
highly scalable systems.

I am highly skilled in python programming language although I have
experience in writing software in other languages as well.
#+END_QUOTE

* Appointments

Senior Developer in the PayamPardaz Company, 2015 -- /Present/

Developer in the AmnGostar Company, 2013 -- 2015

Developer in the PayamPardaz Company, 2011 -- 2013

* Education

Master of Arts in Computer Software Engineering at the University of Isfahan, Iran, 2009 -- 2011

Bachelor of Arts in Computer Software Engineering at the University of Isfahan, Iran, 2005 -- 2009

* Experiences
** Main Contributor

- An [[https://www.rsyslog.com/][Rsyslog]] plugin developed in Golang to send logs with very high
  rates over gRPC channels to a legacy software, 2020 -- /Present/

- Dockerize over 10 software projects with sophisticated network
  communications and disk persistence, 2017 -- 2019

- Plugin-able system with REST API for communication with network
  devices over protocols such as HTTP/HTTPS, SSH, Telnet, SMTP, etc,
  developed with Python, with more than 15 plugins developed
  by dozens of programmers, 2015 -- /Present/

- Bash scripts to implement high availability with [[https://www.linbit.com/drbd/][DRBD]] and [[https://github.com/acassen/keepalived][keepalived]]
  for a complex system with virtual machines, 2015 -- 2016

- A sophisticated build-system with Makefiles and bash/python scripts
  for an XML knowledge base, 2014 -- /Present/

- A Python/Flask project for monitoring and management of a complex
  system with virtual machines and high security concerns with over 50
  API services, 2014 -- 2019

- A high throughput, log collection/management system developed in
  Python with multi-processing/multi-threading design and
  sophisticated pipelines with support for MongoDB, used heavily in
  production in various organizations, some of them with over a
  hundred terabytes of data, 2013 -- /Present/

- A C++ library to implement The Intrusion Detection Message Exchange
  Format ([[https://tools.ietf.org/html/rfc4765][RFC 4765]]), 2012 -- /Present/

** Significant Contributor

- Flexible and customizable Ansible playbooks to setup kubernetes
  clusters and a distributed software with a distributed file system,
  dozens of high available databases and over cluster communications
  with [[https://skupper.io/][skupper]], 2018 -- /Present/

- A [[https://helm.sh/][helm]] plugin to add support for localization, 2019

- Helm charts for dozens of security software components, 2018 -- 2020

- Management Information Base (MIB) files for a complex system, 2018

- Django based web portal for a monitoring system, 2013 -- /Present/

- A scalable, high-available event processing system developed with C++, 2012 -- /Present/

* Open-source

** Activities

- Open-source tools to deploy Greenbone Vulnerability Management ([[https://community.greenbone.net/][GVM]])
  with containers, [[https://github.com/admirito/gvm-containers][gvm-containers]] on my GitHub, 2019 -- /Present/

- Greenbone Vulnerability Management [[https://launchpad.net/~mrazavi/+archive/ubuntu/gvm][Ubuntu PPA]], 2019 -- /Present/

- GitLab CI tools for debian packaging, [[https://github.com/admirito/kayna][kayna]] on my GitHub, 2016 -- /Present/

- [[https://www.backbox.org/][BackBox]] Linux distribution repository maintainer, 2015 -- 2018

- [[https://www.openvas.org/][OpenVAS]] Vulnerability Assessment Scanner community package maintainer, 2015 -- 2018

- Automatic Debian installation system with preseeds, [[https://github.com/admirito/durian][durian]] on my GitHub, 2015

- Various contributions on open-source projects, see my [[https://github.com/admirito/][GitHub]]
