#+TITLE: Curriculum Vitae
#+AUTHOR: Mohammad Razavi
#+KEYWORDS: vita, CV, resume
#+OPTIONS: toc:nil num:nil
#+STARTUP: entitiespretty

#+BEGIN_QUOTE
I am a senior back-end developer with 10 years of experience working
on scalable architectures, distributed computing, big data analytics,
micro services, and cloud infrastructures.

I have worked with teams to develop network and security monitoring
software for organizations ranging from start-ups to national
enterprises.

I excel at team leadership, software development, micro services,
automation and cloud computing.
#+END_QUOTE

* Skills

- Software design and development
- Debugging and troubleshooting
- Optimization and design for scalability
- Strong Linux background
- Networking and cybersecurity knowledge
- Automation and deployment
- Agile software development

* Experiences

** Programming and Software Design

- Lead and participate in the design and development of 4 applications
  with Python and Flask framework with REST API / gRPC service
  methods.

- Refactor and migrate 5 projects with thousands of Python 2 code
  to python 3, add hundreds of new unit tests to legacy software,
  maintain stability in more than 20 production environments.

- [[https://github.com/admirito/pitaya-form][PitayaForm]] on my GitHub: A proposal/specification for defining
  interactive form-based UIs

- Develop 3 applications with Python multiprocessing framework to
  handle CPU intensive tasks on NUMA systems.

- Reimplement a Python tool with Golang to handle loads of up to 10x.

- Developed two related C++ back-end engines for intrusion detection
  and extract the common code into a software library used in other
  projects as well.

- Contribute to the design, implementation and maintenance of an
  SIEM/EDR product with large scale enterprises customers.

- Report bugs and implement accepted merge-requests to fix problems of
  well-established FOSS software in Python, C/C++, Java, etc.

** Data Engineering

- Adapt a data store software with 4 new DBMS and data tools for
  better handling of big loads and more flexible analytics.

- [[https://github.com/admirito/pymongowatch][PyMongoWatch]] on my GitHub: An extension for MongoDB's Python driver
  for auditing.

- Design at least 5 migrations of data schema with JS for a MongoDB
  database with terabytes of data in a production system.

- Design schema, automatic integrity tests and a build-system with
  Makefiles and bash/python scripts for an XML knowledge base with
  over 20 repositories.

- Build a high-throughput fake data generator with Python
  multiprocessing for performance tests.

** DevOps

- Containerize over 10 legacy software projects with more than 50
  containers in total for migration to kubernetes.

- Implement and maintain over 20 helm charts, 50 debian packages and
  4 software repositories.

- [[https://github.com/admirito/gvm-containers][gvm-containers]]: Docker/Kubernetes tools to deploy Greenbone
  Vulnerability Management ([[https://community.greenbone.net/][GVM]]), 80-stars / 50-forks on my GitHub.

- Design and implement an ansible playbook to setup kubernetes with
  MetalLB, CephFS, SQL/NoSQL databases and state-full applications.

- Fork [[https://github.com/skupperproject/skupper-proxy][skupper-proxy]] kubernetes controller FOSS project and add
  features for better maintenance of inter-cluster communications,
  used by the DevOps team.

- [[https://launchpad.net/~mrazavi/+archive/ubuntu/gvm][GVM Ubuntu PPA]]: About 10 C++/Python based debian Packages,
  maintained more than 5 years for hundreds of users.

- [[https://github.com/admirito/kayna][kayna]] on my GitHub: GitLab CI tools for debian packaging.

- Use bash scripts to implement high availability with DRBD and
  keepalived for a system with virtual machines.

* Employment

Senior Developer in the PayamPardaz Company, 2015 -- /Present/

Developer in the AmnGostar Company, 2013 -- 2015

Developer in the PayamPardaz Company, 2011 -- 2013

* Education

Master of Arts in Computer Software Engineering at the University of
Isfahan, Iran, 2009 -- 2011

Bachelor of Arts in Computer Software Engineering at the University of
Isfahan, Iran, 2005 -- 2009

* Community

[[https://www.backbox.org/][BackBox]] Linux distribution repository maintainer, 2015 - 2018

[[https://www.openvas.org/][OpenVAS]] Vulnerability Assessment Scanner community package maintainer,
2015 - 2018

* Honors

ACM International Collegiate Programming Contest (ICPC), Asia region,
Tehran site contestant, 2009

RoboCup, Mixed Reality League, the winner of the 3rd place ribbon,
Suzhou international challenges, 2008
